name: helix
base: core22
adopt-info: helix
license: MPL-2.0
source-code: https://github.com/atomcult/helix-snap
issues: https://github.com/atomcult/helix-snap/issues

title: Helix
website: https://helix-editor.com
summary: Helix is a modal text editor inspired by Vim and Kakoune
description: |
  * Vim-like modal editing
  * Multiple selections
  * Built-in language server support
  * Smart, incremental syntax highlighting and code editing via tree-sitter
  * Written in Rust

grade: stable
confinement: classic

apps:
  helix:
    command: bin/hx

parts:
  helix:
    plugin: rust
    rust-path: [helix-term]
    source: https://github.com/helix-editor/helix.git
    source-tag: "24.03"
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always)"
    build-packages: [cargo, rustc, g++]
    build-attributes:
      - enable-patchelf
    override-build: |
      craftctl default

      # Copy the runtime files
      cp -r "${CRAFT_PART_BUILD}/runtime" "${CRAFT_PART_INSTALL}/bin/"
      rm -r "${CRAFT_PART_INSTALL}/bin/runtime/grammars/sources"

      # Strip executables
      find "${CRAFT_PART_INSTALL}" -type f -executable -exec strip {} \;
