name: Stable Snap Build

on: workflow_dispatch

jobs:
  build_snap:
    name: Build job for stable Helix snap
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build snap
        uses: snapcore/action-build@v1
        with:
          build-info: true
          snapcraft-channel: latest/stable
        id: build-snap
      - run: |
          sudo snap install --dangerous --classic ${{ steps.build-snap.outputs.snap }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helix-snap
          path: ${{ steps.build-snap.outputs.snap }}
