name: Weekly Snap Build

on:
  schedule:
    - cron: '0 13 * * 6'
  workflow_dispatch:

jobs:
  build_snap:
    name: Build job for weekly Helix snap
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: weekly
      - name: Build snap
        uses: snapcore/action-build@v1
        with:
          build-info: true
          snapcraft-channel: latest/stable
        id: build-snap
      - run: |
          sudo snap install --dangerous --classic ${{ steps.build-snap.outputs.snap }}
      - name: Publish to Edge
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helix-snap
          path: ${{ steps.build-snap.outputs.snap }}
